import _ from 'lodash'
import { MethodNotAllowed, NotFound } from '@feathersjs/errors'

import app from '../../app'
import { truncateTestDatabase } from '../../../db/index'
import { farmData, insertFarm } from './data/farms'
import { createTestUser } from './data/users'

// disable auth
jest.mock('../../hooks/authorization')
jest.mock('../../hooks/email')

describe('farms service', () => {
  const service = app.service('farms')

  const params = { provider: 'rest', headers: {}, query: {} }

  it('gets registered', () => {
    expect(service).toBeTruthy()
  })

  it('finds farms', async () => {
    const farms = await Promise.all(_.times(3, insertFarm))

    const result = await service.find(params)
    expect(result.features).toHaveLength(3)
    farms.forEach(farm => {
      // TODO toJSON is required to get the final representation generated by Objection
      // maybe it's preferrable to convert to GeoJSON in a hook instead, outside of
      // Objection?
      const feature = result.features.find(f => f.id === farm.id).toJSON()
      expect(feature.properties.name).toEqual(farm.name)
      expect(feature.properties.city).toEqual(farm.city)
      expect(feature.geometry.coordinates[0]).toEqual(farm.longitude)
      expect(feature.geometry.coordinates[1]).toEqual(farm.latitude)
    })
  })

  it('gets a farm', async () => {
    const farm = await insertFarm()

    const result = await service.get(farm.id, params)

    expect(result).not.toBeNull()

    const feature = await result.toJSON()

    expect(feature.properties.name).toEqual(farm.name)
    expect(feature.properties.city).toEqual(farm.city)
    expect(feature.geometry.coordinates[0]).toEqual(farm.longitude)
    expect(feature.geometry.coordinates[1]).toEqual(farm.latitude)
    // TODO doesn't work in console??
    // expect(feature.properties.address).toEqual(farm.address)
    // expect(feature.properties.description).toEqual(farm.description)
    // expect(feature.properties.deliveryDays).toEqual(farm.deliveryDays)
  })

  it('creates a farm', async () => {
    params.user = await createTestUser(app.service('users'))

    const data = await farmData()

    const result = await service.create(data, params)

    // TODO shouldn't this return GeoJSON as well?
    expect(result.name).toEqual(data.name)
    expect(result.city).toEqual(data.city)
    expect(Number(result.longitude)).toEqual(data.longitude)
    expect(Number(result.latitude)).toEqual(data.latitude)
    // TODO doesn't work in console??
    // expect(result.address).toEqual(result.address)
    // expect(result.description).toEqual(data.description)
    // expect(result.deliveryDays).toEqual(data.deliveryDays)

  })
  it('patches a farm', async () => {
    params.user = await createTestUser(app.service('users'))

    const testfarm = await insertFarm()
    const patch = await farmData()

    const result = await service.patch(testfarm.id, patch, params)

    expect(result.name).toEqual(patch.name)
    expect(result.city).toEqual(patch.city)
    expect(Number(result.longitude)).toEqual(patch.longitude)
    expect(Number(result.latitude)).toEqual(patch.latitude)
    // TODO doesn't work in console??
    // expect(result.address).toEqual(patch.address)
    // expect(result.description).toEqual(patch.description)
    // expect(result.deliveryDays).toEqual(patch.deliveryDays)

  })

  it('disallows update', async () => {
    await expect(service.update(1, {}, params)).rejects.toThrow(
      MethodNotAllowed
    )
  })

  it('removes a farm', async () => {
    params.user = await createTestUser(app.service('users'))

    const testfarm = await insertFarm()

    const result = await service.remove(testfarm.id, params)
    expect(result.name).toEqual(testfarm.name)
    expect(result.city).toEqual(testfarm.city)
    expect(Number(result.longitude)).toEqual(testfarm.longitude)
    expect(Number(result.latitude)).toEqual(testfarm.latitude)
    // TODO doesn't work in console??
    // expect(result.address).toEqual(testfarm.address)
    // expect(result.description).toEqual(testfarm.description)
    // expect(result.deliveryDays).toEqual(testfarm.deliveryDays)

    await expect(service.get(testfarm.id, params)).rejects.toThrow(NotFound)

  })

  afterEach(async () => truncateTestDatabase())
})
