name: Deploy Preview to Production (Fast-Forward Merge)

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Select the main branch to run this workflow.'
        required: true
        default: 'This workflow should only be triggered from the main branch.'

permissions:
  contents: write # Allows the workflow to push to the repository
  actions: write # Allows the workflow to trigger other workflows

jobs:
  fast-forward-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch origin

      - name: Fast-forward merge preview into main
        run: |
          git checkout main
          git merge --ff-only origin/preview
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for merge to complete
        run: sleep 10

      - name: Trigger Map CI Production Deployment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'map-ci.yml',
              ref: 'main'
            });

      - name: Trigger API CI Production Deployment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'api-ci.yml',
              ref: 'main'
            });

      - name: Trigger Admin CI Production Deployment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'admin-ci.yml',
              ref: 'main'
            });
